version: "3"

services:
  db:
    image: postgres:14.13-alpine3.20
    container_name: share_qr_db
    ports:
      - ${DB_PORT}:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}

volumes:
  dbdata: